from __future__ import annotations

from collections.abc import Sequence
from typing import TypedDict

IndexedDecryptedRTPPacket = tuple[int, int, bool, bool, int, int, int, bool, bytes, tuple[tuple[int, bytes], ...], bytes]

class DesktopCaptureStats(TypedDict):
    framesReadTotal: int
    framesCapturedTotal: int
    framesCopiedTotal: int
    framesReusedTotal: int
    pointerUpdatesTotal: int
    captureAttemptsTotal: int
    captureTimeoutsTotal: int
    captureCallMeanMs: float
    captureCallMaxMs: float
    nv12ConversionCount: int
    nv12ConversionMeanMs: float
    nv12ConversionMaxMs: float
    frameIntervalsCount: int
    frameIntervalMeanMs: float
    frameIntervalStdevMs: float

class TransportCrypto:
    def __init__(self, mode: str, key: bytes) -> None: ...
    def encrypt_rtp(self, header: bytes, payload: bytes) -> bytes: ...
    def encrypt_rtcp(self, header: bytes, payload: bytes) -> bytes: ...
    def decrypt_rtcp_packets(self, packet: bytes, header_len: int) -> tuple[tuple[int, int, int, bytes], ...]: ...
    def decrypt_rtp_packets(
        self,
        packets: Sequence[bytes],
    ) -> tuple[int, tuple[IndexedDecryptedRTPPacket, ...]]: ...

class VideoSendPipeline:
    def __init__(self) -> None: ...
    def configure_stream(
        self,
        codec: str,
        media_ssrc: int,
        payload_type: int,
        rtx_payload_type: int | None,
        rtx_ssrc: int,
        rid: str,
    ) -> None: ...
    def retain_streams(self, media_ssrcs: list[int]) -> None: ...
    def clear(self) -> None: ...
    def has_stream(self, media_ssrc: int) -> bool: ...
    def current_timestamp(self, media_ssrc: int) -> int: ...
    def send_video_frame(
        self,
        crypto: TransportCrypto,
        fd: int,
        media_ssrc: int,
        frame: bytes,
        metadata_frame: bytes | None,
        frame_time_ms: float,
        media_stream_type: str,
        burst_size: int,
        burst_interval: float,
    ) -> tuple[int, int, int, int, int | None]: ...
    def send_video_rtx_packet(
        self,
        crypto: TransportCrypto,
        fd: int,
        media_ssrc: int,
        sequence: int,
        media_stream_type: str,
    ) -> tuple[bool, int, int, int]: ...
    def send_video_rtx_for_nack(
        self,
        crypto: TransportCrypto,
        fd: int,
        payload: bytes,
        media_stream_type: str,
        burst_size: int,
        burst_interval: float,
    ) -> tuple[int, int, int, int, int]: ...

class NativeUDPTransport:
    ping_rtt_ms: float | None
    ping_timeouts: int
    ping_send_errors: int
    def __init__(self, buffer_size: int | None = ..., tos: int | None = ...) -> None: ...
    def fileno(self) -> int: ...
    def connect(self, address: str, port: int) -> None: ...
    def discover_ip(self, ssrc: int, timeout: float) -> tuple[str, int]: ...
    def add_listener(self, callback: object, rtp: bool, rtcp: bool) -> int: ...
    def add_batch_listener(self, callback: object, rtp: bool, rtcp: bool) -> int: ...
    def remove_listener(self, id: int) -> None: ...
    def send_packet(self, packet: bytes) -> None: ...
    def send_packets(self, packets: Sequence[bytes]) -> tuple[int, int]: ...
    def start_ping(self, initial_delay: float, interval: float, timeout: float) -> None: ...
    def stop_ping(self) -> None: ...
    def stats(self) -> dict[str, int]: ...
    def close(self) -> None: ...

class H264Depacketizer:
    def push_packet(self, payload: bytes, marker: bool, sequence: int, timestamp: int) -> bytes | None: ...

class H265Depacketizer:
    def push_packet(self, payload: bytes, marker: bool, sequence: int, timestamp: int) -> bytes | None: ...

class VP8Depacketizer:
    def push_packet(self, payload: bytes, marker: bool, sequence: int, timestamp: int) -> bytes | None: ...

class VP9Depacketizer:
    def push_packet(self, payload: bytes, marker: bool, sequence: int, timestamp: int) -> bytes | None: ...

class AV1Depacketizer:
    def push_packet(self, payload: bytes, marker: bool, sequence: int, timestamp: int) -> bytes | None: ...

class DesktopFrameSource:
    width: int
    height: int
    frame_size: int
    pixel_format: str
    preferred_read_size: int
    def __init__(self, output_index: int, fps: int) -> None: ...
    def set_pixel_format(self, pixel_format: str) -> None: ...
    def read(self, size: int) -> bytes: ...
    def write_to_handle(self, handle: int) -> dict[str, int | float]: ...
    def pipe_stats(self) -> dict[str, int | float]: ...
    def stats(self) -> DesktopCaptureStats: ...
    def close(self) -> None: ...

def pcm16_add(left: bytes, right: bytes) -> bytes: ...
def pcm16_mul(data: bytes, factor: float) -> bytes: ...
def pcm16_mix(chunks: list[bytes]) -> bytes: ...
def strip_h264_filler_nalus(frame: bytes) -> bytes: ...
